### PR TITLE
Support area charts and custom interpolations

### PR DESCRIPTION
**Pull request by bclinkinbeard**
I tried changing the code to `<INNER_CHART data={data} {...this.props}>` to support any custom props we might want to pass but that caused problems with the axes. If you know how to avoid that and support arbitrary props that would be cool.

### CODE REVIEW

**Comment by mathisonian** [comment]
I think its most likely setting some properties on both the chart wrapper and the inner chart obj that is leading to confusion with the axes (and we also may pass a modified `this.props.data`), this should to work:

```
<INNER_CHART data={data} {...getObjWithoutProps(this.props, ['data', 'scale', 'domain'])}>
```

assuming `getObjWithoutProps` is a function that returns a copy of the object without those listed properties

**Comment by bclinkinbeard** [comment]
Cool, looks like you were right.

I updated the project from `babel-preset-es2105` to `babel-preset-env` since that is now the recommended approach, and I added `babel-preset-stage-2` so I could use object spread syntax for `getObjWithoutProps`.

**Comment by bclinkinbeard** [comment]
Any objections to this @mathisonian?

**Comment by mathisonian** [comment]
No objections - but I want to make sure the babel presets we use here match those in the main Idyll project, so I'll update those as well

**Comment by bclinkinbeard** [comment]
Cool, I've been meaning to update all of them too.

**Pull request merged**
